Repository AnswerDotAI/fasthtml, pull requests merged in 2024-08, with the labels that each got.

#145 Add htmlkw to fast_app
  fasthtml/fastapp.py
Labels: enhancement

#213 Wrap Starlette's session in an AttrDict
  fasthtml/_modidx.py
  fasthtml/core.py
  nbs/api/00_core.ipynb
Labels: enhancement

#230 railway deploy doesn't check for project name
  fasthtml/cli.py
  nbs/api/09_cli.ipynb
Labels: bug

#234 feat: (#225) Add support for application/json in POST requests
  fasthtml/core.py
  nbs/api/00_core.ipynb
Labels: enhancement

#221 Use re.fullmatch for Beforeware
  fasthtml/core.py
  nbs/api/00_core.ipynb
Labels: bug

#335 404 handling
  fasthtml/core.py
  nbs/api/00_core.ipynb
Labels: enhancement

#378 Make improvements to `FastHTML By Example`
  nbs/tutorials/by_example.ipynb
Labels: documentation
