Repository AnswerDotAI/fasthtml, pull requests merged in 2024-10, with the labels that each got.

#481 Tutorial: Jupyter and FastHTML
  nbs/tutorials/jupyter_and_fasthtml.ipynb
Labels: documentation

#505 Add path
  fasthtml/jupyter.py
  nbs/api/06_jupyter.ipynb
Labels: enhancement

#490 Add file upload to quickstart
  nbs/tutorials/quickstart_for_web_devs.ipynb
Labels: documentation

#511 Allows for passing route functions
  fasthtml/jupyter.py
  nbs/api/06_jupyter.ipynb
Labels: enhancement

#518 Adding mermaidJS for mermaid graphs
  fasthtml/_modidx.py
  fasthtml/js.py
  nbs/api/03_js.ipynb
Labels: enhancement

#526 Allow toasts to work with FtResponse
  fasthtml/toaster.py
  nbs/tutorials/quickstart_for_web_devs.ipynb
  tests/test_toaster.py
Labels: enhancement

#551 Add nb_hdrs to fast_app
  fasthtml/fastapp.py
Labels: bug
