Repository AnswerDotAI/fasthtml, pull requests merged in 2024-11, with the labels that each got.

#552 Minidata API Spec cleanup
  nbs/explains/minidataapi.ipynb
  nbs/tutorials/quickstart_for_web_devs.ipynb
Labels: documentation

#570 handle oauth error
  fasthtml/oauth.py
  nbs/api/08_oauth.ipynb
Labels: bug

#588 use % notation instead of .format in toast js & livereload js
  fasthtml/live_reload.py
  fasthtml/toaster.py
Labels: cleanup
