Repository AnswerDotAI/fasthtml, pull requests merged in 2025-04, with the labels that each got.

#692 Redux background tasks fix+docs
  fasthtml/core.py
  nbs/api/00_core.ipynb
  nbs/explains/background_tasks.ipynb
Labels: bug, documentation

#702 Document in concise guide how to use MonsterUI with highlighted code
  nbs/ref/concise_guide.ipynb
Labels: documentation

#704 inserts toasts at top of the page
  fasthtml/toaster.py
  nbs/tutorials/quickstart_for_web_devs.ipynb
  tests/test_toaster.py
Labels: bug

#716 Fix Discord Client
  fasthtml/oauth.py
  nbs/api/08_oauth.ipynb
Labels: bug
