Repository AnswerDotAI/fasthtml, pull requests merged in 2025-01, with the labels that each got.

#636 fixes #633
  fasthtml/core.py
  fasthtml/core.pyi
  nbs/api/00_core.ipynb
Labels: bug

#644 Update handlers.ipynb
  nbs/ref/handlers.ipynb
Labels: documentation

#638 Handling for query or url params in qp/to
  fasthtml/core.py
  nbs/api/00_core.ipynb
Labels: enhancement
