Repository AnswerDotAI/fasthtml, pull requests merged in 2025-03, with the labels that each got.

#665 Change links for new URL scheme
  README.md
  fasthtml/_modidx.py
  nbs/_quarto.yml
  nbs/api/08_oauth.ipynb
  nbs/apilist.txt
  nbs/explains/faq.ipynb
  nbs/index.ipynb
  nbs/llms-ctx-full.txt
  nbs/llms-ctx.txt
  nbs/llms.txt
  nbs/nbdev.yml
  nbs/ref/handlers.ipynb
  nbs/ref/live_reload.ipynb
  nbs/robots.txt
  nbs/tutorials/quickstart_for_web_devs.ipynb
  settings.ini
Labels: documentation

#680 Improve FastHTML concise guide
  drafts/concise_guide.ipynb
Labels: documentation

#682 Enhance Concise Guide
  nbs/ref/concise_guide.ipynb
Labels: documentation

#685 Add missing monsterui dev dependency
  settings.ini
Labels: bug

#658 Add response types reference page
  nbs/ref/response_types.ipynb
Labels: documentation

#651 handle for when there is a type hint on session
  fasthtml/core.py
  nbs/api/00_core.ipynb
  tests/test_toaster.py
Labels: enhancement

#666 Stripe Tutorial
  nbs/explains/CreateWebhook.png
  nbs/explains/CreateWebhook2.png
  nbs/explains/Stripe.ipynb
  nbs/explains/StripeDashboard_API_Key.png
  nbs/explains/StripePaymentPage.jpg
  nbs/explains/SubscriptionEvents.png
  nbs/explains/refund.png
  nbs/explains/stripe_otp.py
Labels: documentation

#674 Fix+docs for background tasks when used by FtResponse
  fasthtml/core.py
  nbs/api/00_core.ipynb
  nbs/explains/background_tasks.ipynb
Labels: bug, documentation

#694 update `_formitem` so that it doesn't raise `KeyError`
  fasthtml/core.py
  nbs/api/00_core.ipynb
Labels: bug

#696 Monsterui concise guide additions
  nbs/ref/concise_guide.ipynb
Labels: documentation
